version: 2
jobs:
  build:
    docker:
      - image: bitnami/laravel
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install netcat -y
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
  deploy:
    machine:
      enabled: true
    steps:
      - run:    
          name: Deploy
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /var/www/sites/lara6-docker && git pull"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build
          filters:
            branches:
              only: master
        
